### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: stream did not contain valid UTF-8', src/main.rs:102:61

### ISSUE THREAD

**Issue by subwaystation** [chfi/gfaestus#1]
Hi @chfi 
Running 

```
./target/release/gfaestus ~/Downloads/yeast/pggb_gfaestus/cerevisiae.pan.fa.pggb-W-s50000-l150000-p90-n5-a0-K16.seqwish-k8-B10000000.smooth-w30000-j5000-e5000-I0.7-p1_4_6_2_26_1.gfa ~/Downloads/yeast/pggb_gfaestus/cerevisiae.pan.fa.pggb-W-s50000-l150000-p90-n5-a0-K16.seqwish-k8-B10000000.smooth-w30000-j5000-e5000-I0.7-p1_4_6_2_26_1.chop.og.lay
```

I see
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: stream did not contain valid UTF-8', src/main.rs:102:61
```
Link to the data. Will expire in 10 days.
http://fex.belwue.de/fop/LTIrSTM5/pggb_gfaestus_issue.zip

Thanks for any feedback!

**Comment by AndreaGuarracino** [comment]
The input layout must be in TSV text format.

**Comment by subwaystation** [comment]
Good to know, thanks!
