### ISSUE TITLE
Error loading GFA file

### ISSUE THREAD

**Issue by brettChapman** [chfi/gfaestus#2]
Hi

I'm trying to load my GFA file, but I'm getting an error.

```
gfaestus *.smooth.gfa *.smooth.chop.og.lay
loading GFA
loading GFA with 734 nodes, 1003 edges
adding nodes
adding edges
adding paths
created path handles
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: stream did not contain valid UTF-8', src/main.rs:116:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

echo $RUST_BACKTRACE
1 
```

I've also set the environment variable RUST_BACKTRACE=1 but still get no more information about the error.

I'm trying to visualise graphs produced from PGGB (https://github.com/pangenome/pggb). At the moment I'm only looking at small graphs representing a gene region. Thanks for any help you can provide.

**Comment by chfi** [comment]
You need to have odgi output the layout file in TSV format (I think it's the -T command line flag)

// Christian

-------- Original Message --------

**Comment by brettChapman** [comment]
Thanks. I managed to generate a TSV formatted layout file.

After running I now get a different error message:
```
gfaestus *.smooth-w400000-j10000-e10000-I0.9-p1_4_6_2_26_1.gfa *.smooth-w400000-j10000-e10000-I0.9-p1_4_6_2_26_1.chop.og.lay.tsv
loading GFA
loading GFA with 791 nodes, 1083 edges
adding nodes
adding edges
adding paths
created path handles
layout bounding box	(1000.00, 1000.00)	(6212.05, 1051.36)
layout width: 5212.05	height: 51.36
GFA loaded in 0.016 sec
Loaded 791 nodes	1582 points
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LoadingError(LibraryLoadFailure("dlopen(libvulkan.1.dylib, 1): image not found"))', src/main.rs:152:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by chfi** [comment]
If you're on Mac, you need to have MoltenVK installed https://github.com/KhronosGroup/MoltenVK

// Christian

-------- Original Message --------

**Comment by brettChapman** [comment]
Hi, I've been trying to get the MoltenVK libraries installed on my Mac with no success. It doesn't look very straight forward to install the libraries.

I've tried:
```
xcodebuild build -quiet -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (macOS only)" -configuration "Debug"
```
And then running gfaestus again, but I still get the same error about loading libvulkan.1.dylib.

My MacBook Pro is running Catalina 10.15.7. 

Is there a more straight forward way to install, perhaps through homebrew or similar? Thanks.

**Comment by brettChapman** [comment]
I realised I hadn't installed dependencies. So I tried this:

```
./fetchDependencies --macos
sudo make macos
sudo make install
```

I still get the same error about libvulkan.1.dylib image not found.

**Comment by subwaystation** [comment]
I have a similar problem with today's master, rust 1.51.0 and Archlinux:

```
gfaestus cerevisiae.pan.fa.aed9ce4.34ee7b1.891e76b.smooth.gfa cerevisiae.pan.fa.aed9ce4.34ee7b1.891e76b.smooth.og.lay.tsv
loading GFA
loading GFA with 636434 nodes, 878055 edges
adding nodes
adding edges
adding paths
created path handles
layout bounding box	(1000.00, 1000.00)	(1533269.38, 1849298.75)
layout width: 1532269.38	height: 1848298.75
GFA loaded in 4.641 sec
Loaded 636434 nodes	1272868 points
thread 'main' panicked at 'Validation layer not supported: VK_LAYER_KHRONOS_validation', src/vulkan/debug.rs:73:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Currently happening with all data sets I tried. Happy to share if you need some.

**Comment by chfi** [comment]
> I realised I hadn't installed dependencies. So I tried this:
> 
> ```
> ./fetchDependencies --macos
> sudo make macos
> sudo make install
> ```
> 
> I still get the same error about libvulkan.1.dylib image not found.

I don't have a Mac, so I can't really help. I'd suggest trying another Vulkan app (these examples are easy to build: https://github.com/SaschaWillems/Vulkan); if they work, there's probably something wrong with gfaestus

**Comment by chfi** [comment]
> I have a similar problem with today's master, rust 1.51.0 and Archlinux:
> 
> ```
> gfaestus cerevisiae.pan.fa.aed9ce4.34ee7b1.891e76b.smooth.gfa cerevisiae.pan.fa.aed9ce4.34ee7b1.891e76b.smooth.og.lay.tsv
> loading GFA
> loading GFA with 636434 nodes, 878055 edges
> adding nodes
> adding edges
> adding paths
> created path handles
> layout bounding box	(1000.00, 1000.00)	(1533269.38, 1849298.75)
> layout width: 1532269.38	height: 1848298.75
> GFA loaded in 4.641 sec
> Loaded 636434 nodes	1272868 points
> thread 'main' panicked at 'Validation layer not supported: VK_LAYER_KHRONOS_validation', src/vulkan/debug.rs:73:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Currently happening with all data sets I tried. Happy to share if you need some.

I think it's because it needs the Vulkan SDK, I'd accidentally set it up so even `release` builds use the debug features from the SDK. 

Latest master should work without the SDK (though you may still need it to compile the shaders)

**Comment by subwaystation** [comment]
Got it. Now it works for me, thank you very much @chfi !
