### ISSUE TITLE
Compilation problem -> Execution problem

### ISSUE THREAD

**Issue by AndreaGuarracino** [chfi/gfaestus#4]
Hi Chris,

on my system (Ubuntu 20.04), doing

```
git clone --recursive https://github.com/chfi/gfaestus.git
cd gfaestus/
RUST_BACKTRACE=full cargo build --release
```

I get

```
[...]
   Compiling gif v0.11.1
   Compiling tokio v0.2.25
   Compiling dlib v0.4.2
   Compiling ash v0.31.0

error: failed to run custom build command for `gfaestus v0.1.0 (/home/guarracino/git/gfaestus)`

Caused by:
  process didn't exit successfully: `/home/guarracino/git/gfaestus/target/release/build/gfaestus-432db26c746973b7/build-script-build` (exit code: 101)
  --- stdout
  Compiling shaders...

  --- stderr
  thread 'main' panicked at 'Failed to compile shader. Cause: No such file or directory (os error 2)', build.rs:83:13
  stack backtrace:
     0:     0x5613d4e065b0 - std::backtrace_rs::backtrace::libunwind::trace::h74532f8b485906a1
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x5613d4e065b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2c8425dd0be5999b
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5613d4e065b0 - std::sys_common::backtrace::_print_fmt::hd8ce6577f46119ce
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x5613d4e065b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6289eeebc1f97d57
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x5613d4e20e0f - core::fmt::write::h3d3f8a8bb9d4c367
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/fmt/mod.rs:1092:17
     5:     0x5613d4e03c52 - std::io::Write::write_fmt::ha117cbfa72664a7b
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:1572:15
     6:     0x5613d4e08285 - std::sys_common::backtrace::_print::h112e8a4ac2720a21
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x5613d4e08285 - std::sys_common::backtrace::print::h2a4ab5824600ebce
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x5613d4e08285 - std::panicking::default_hook::{{closure}}::h399ab06c3b83a1f2
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:208:50
     9:     0x5613d4e07d33 - std::panicking::default_hook::h7481e93ca9c2d739
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:225:9
    10:     0x5613d4e0888d - std::panicking::rust_panic_with_hook::h01f9d4e9485ccb8b
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:591:17
    11:     0x5613d4e08427 - std::panicking::begin_panic_handler::{{closure}}::h25bff4eb752cc444
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:497:13
    12:     0x5613d4e06a6c - std::sys_common::backtrace::__rust_end_short_backtrace::h5dfd3f7920e58cc5
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x5613d4e08389 - rust_begin_unwind
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
    14:     0x5613d4de1eab - std::panicking::begin_panic_fmt::h5ea05d30b78d4fb2
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:435:5
    15:     0x5613d4de536e - build_script_build::handle_program_result::hd616f239f03b87e5
    16:     0x5613d4de4c1a - build_script_build::compile_shaders::{{closure}}::h6a21294b2d2e3036
    17:     0x5613d4de6612 - core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::hdba9e6f844b18f25
    18:     0x5613d4de8666 - core::iter::adapters::filter::filter_fold::{{closure}}::hd2335b6a7e938309
    19:     0x5613d4deb13d - core::iter::adapters::map::map_fold::{{closure}}::h5a9825aac41bb721
    20:     0x5613d4deb709 - core::iter::traits::iterator::Iterator::fold::h676a543d465bc74a
    21:     0x5613d4deacb1 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h9480345f9c19c8e0
    22:     0x5613d4de7f91 - <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::fold::h9da373dcdbf0f4b1
    23:     0x5613d4de8562 - core::iter::traits::iterator::Iterator::for_each::hb13b215b1fca0e15
    24:     0x5613d4de4716 - build_script_build::compile_shaders::h4aaa1f5a16508b64
    25:     0x5613d4de448e - build_script_build::main::h71df4c9e67a911fe
    26:     0x5613d4de9253 - core::ops::function::FnOnce::call_once::hfb05eaca16c55879
    27:     0x5613d4de8739 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7e77a3f26319a990
    28:     0x5613d4de5b09 - std::rt::lang_start::{{closure}}::ha0e46fb4d0791a39
    29:     0x5613d4e08c8a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha7db63b609be77e3
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:259:13
    30:     0x5613d4e08c8a - std::panicking::try::do_call::h715c8c8ca0806d14
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:379:40
    31:     0x5613d4e08c8a - std::panicking::try::h2530c507ef432acf
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:343:19
    32:     0x5613d4e08c8a - std::panic::catch_unwind::h0c4984a63ffdd417
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panic.rs:431:14
    33:     0x5613d4e08c8a - std::rt::lang_start_internal::h12392519f60c6396
                                 at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/rt.rs:51:25
    34:     0x5613d4de5af1 - std::rt::lang_start::h4aa2d3928c63fb01
    35:     0x5613d4de5543 - main
    36:     0x7f2cd85770b3 - __libc_start_main
    37:     0x5613d4de290e - _start
    38:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
```

The problem happens with Rust 1.51.0 and 1.52.0.

Do you have any clues?

**Comment by chfi** [comment]
I think it's because `glslangValidator`, which is used to compile the shaders, is missing. It's part of the Vulkan SDK: https://vulkan.lunarg.com/

Latest commit adds a check and a better error message

**Comment by AndreaGuarracino** [comment]
That's right! Now I am able to compile, but I have a new problem

```
loading GFA
loading GFA with 632837 nodes, 854989 edges
adding nodes
adding edges
adding paths
created path handles
layout bounding box	(1000.00, 1000.00)	(1525621.00, 1421614.12)
layout width: 1524621.00	height: 1420614.12
GFA loaded in 5.983 sec
Loaded 632837 nodes	1265674 points
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Selected physical device: "Intel(R) UHD Graphics 630 (CFL GT2)"
Creating swapchain.
	Format: B8G8R8A8_UNORM
	ColorSpace: SRGB_NONLINEAR
	PresentMode: MAILBOX
	Extent: Extent2D { width: 800, height: 600 }
	ImageCount: 4
[src/main.rs:219]
recreating swapchain
Creating swapchain.
	Format: B8G8R8A8_UNORM
	ColorSpace: SRGB_NONLINEAR
	PresentMode: MAILBOX
	Extent: Extent2D { width: 800, height: 600 }
	ImageCount: 4
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/guarracino/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/window.rs:1006:14
stack backtrace:
   0:     0x55b263152bc0 - std::backtrace_rs::backtrace::libunwind::trace::h74532f8b485906a1
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b263152bc0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2c8425dd0be5999b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b263152bc0 - std::sys_common::backtrace::_print_fmt::hd8ce6577f46119ce
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b263152bc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6289eeebc1f97d57
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b263175f8f - core::fmt::write::h3d3f8a8bb9d4c367
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/fmt/mod.rs:1092:17
   5:     0x55b26314f4c2 - std::io::Write::write_fmt::ha117cbfa72664a7b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:1572:15
   6:     0x55b263154e85 - std::sys_common::backtrace::_print::h112e8a4ac2720a21
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b263154e85 - std::sys_common::backtrace::print::h2a4ab5824600ebce
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b263154e85 - std::panicking::default_hook::{{closure}}::h399ab06c3b83a1f2
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:208:50
   9:     0x55b263154933 - std::panicking::default_hook::h7481e93ca9c2d739
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:225:9
  10:     0x55b26315548d - std::panicking::rust_panic_with_hook::h01f9d4e9485ccb8b
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:591:17
  11:     0x55b263155027 - std::panicking::begin_panic_handler::{{closure}}::h25bff4eb752cc444
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:497:13
  12:     0x55b26315307c - std::sys_common::backtrace::__rust_end_short_backtrace::h5dfd3f7920e58cc5
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b263154f89 - rust_begin_unwind
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
  14:     0x55b262983d81 - core::panicking::panic_fmt::h5673e42e796a7b06
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
  15:     0x55b262983c73 - core::option::expect_none_failed::h07f0652cb668bd4d
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/option.rs:1329:5
  16:     0x55b263068c9f - winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical::h2e0d8e253205c30a
  17:     0x55b2629d951f - gfaestus::vulkan::GfaestusVk::draw_frame_from::hd2c7190c06a84787
  18:     0x55b2629c5058 - gfaestus::main::{{closure}}::h961356091a0bf374
  19:     0x55b2629d27bb - winit::platform_impl::platform::x11::EventLoop<T>::run::h5f0b7b98cd8197f1
  20:     0x55b2629c20e8 - winit::platform_impl::platform::EventLoop<T>::run::hfd1264fc7a45fb9b
  21:     0x55b26299d250 - winit::event_loop::EventLoop<T>::run::h774c687c90cdd0ff
  22:     0x55b26299fd74 - gfaestus::main::h5c9b3b26b9195d87
  23:     0x55b262996683 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd08d722fcbe6a1b4
  24:     0x55b262996699 - std::rt::lang_start::{{closure}}::h9ce0d7bc1b1e4967
  25:     0x55b26315598a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha7db63b609be77e3
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:259:13
  26:     0x55b26315598a - std::panicking::try::do_call::h715c8c8ca0806d14
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:379:40
  27:     0x55b26315598a - std::panicking::try::h2530c507ef432acf
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:343:19
  28:     0x55b26315598a - std::panic::catch_unwind::h0c4984a63ffdd417
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panic.rs:431:14
  29:     0x55b26315598a - std::rt::lang_start_internal::h12392519f60c6396
                               at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/rt.rs:51:25
  30:     0x55b2629a0152 - main
  31:     0x7f9dcd8240b3 - __libc_start_main
  32:     0x55b26298446e - _start
  33:                0x0 - <unknown>
```

**Comment by chfi** [comment]
Hmm strange, it looks like the window is being destroyed or something, not sure what's going on :/

See if the examples in the ash repo work: https://github.com/MaikKlein/ash

**Comment by AndreaGuarracino** [comment]
Still not sure what is wrong with my system.

```
RUST_BACKTRACE=full ~/git/gfaestus/target/release/gfaestus rick_E_REF_chr19_32000000_32600000.og.burn.gfa rick_E_REF_chr19_32000000_32600000.og.burn.og.lay.tsv
loading GFA
loading GFA with 44988 nodes, 65172 edges
adding nodes
adding edges
adding paths
created path handles
creating universe
loading layout
layout bounding box	(1000.00, 1000.00)	(658365.81, 38988.32)
layout width: 657365.81	height: 37988.32
GFA loaded in 1.725 sec
Loaded 44988 nodes	89976 points
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Selected physical device: "Intel(R) UHD Graphics 630 (CFL GT2)"
graphics_ix: 0
present_ix: 0
compute_ix: 0
graphics_queue: 0x55f20c8e9e88
present_queue: 0x55f20c8e9e88
compute_queue: 0x55f20c8e9e88
node count 44988
GluonVM eval_line
REPL eval_line_
REPL eval_line_ value
{ open_file: <open_file>, create_file: <create_file>, functor: { map: <functor>, }, applicative: { functor: { map: <functor>, }, apply: <apply>, wrap: <wrap>, }, monad: { applicative: { functor: { map: <functor>, }, apply: <apply>, wrap: <wrap>, }, flat_map: <flat_map>, }, read: { read: <extern read_file>, read_to_end: <extern read_file_to_end>, }, write: { write_slice: <extern write_slice_file>, flush: <extern flush_file>, }, disposable: { dispose: <extern close_file>, is_disposed: <extern is_file_closed>, }, flat_map: <flat_map>, wrap: <wrap>, open_file_with: <extern open_file_with>, read_file_to_string: <extern read_file_to_string>, read_file_to_array: <extern read_file_to_array>, read_file: <extern read_file>, read_file_to_end: <extern read_file_to_end>, write_slice_file: <extern write_slice_file>, flush_file: <extern flush_file>, close_file: <extern close_file>, is_file_closed: <extern is_file_closed>, read_char: <extern read_char>, read_line: <extern read_line>, print: <extern print>, println: <extern println>, flush_stdout: <extern flush_stdout>, eprint: <extern eprint>, eprintln: <extern eprintln>, catch: <extern catch>, throw: <extern throw>, run_expr: <extern run_expr>, load_script: <extern load_script>, default_buf_len: 8192, }
GluonVM eval_line
REPL eval_line_
REPL eval_line_ value
{ goto_selection: <extern goto_selection>, }
[src/vulkan/draw_system/edges.rs:273]
[src/vulkan/draw_system/edges.rs:332]
[src/vulkan/draw_system/edges.rs:336]
added 130344 edges
[src/main.rs:288]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/guarracino/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/window.rs:1006:14
stack backtrace:
   0:     0x55f209b8fce0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f209b8fce0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f209b8fce0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f209b8fce0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f209bb65dc - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55f209b8c085 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55f209b91f2b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f209b91f2b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f209b91f2b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55f209b91a01 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55f209b925f4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55f209b920d7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x55f209b901dc - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f209b92039 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55f2092d0821 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55f2092d0913 - core::result::unwrap_failed::h6160d2b4bfbb0e87
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
  16:     0x55f209a2a5cf - winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical::hd151dcd5c9beebfb
  17:     0x55f2093004bd - gfaestus::vulkan::GfaestusVk::draw_frame_from::h25d2c9860c6841f8
  18:     0x55f209303ebe - gfaestus::main::{{closure}}::h2977570089a06d41
  19:     0x55f2092e42e1 - winit::platform_impl::platform::x11::EventLoop<T>::run::hd0c417a8d44d11bb
  20:     0x55f2092fe996 - winit::platform_impl::platform::EventLoop<T>::run::h4c770f14397c5052
  21:     0x55f2092f7032 - winit::event_loop::EventLoop<T>::run::h4652668ece936cac
  22:     0x55f2092fbd70 - gfaestus::main::h1118d4efde5890d4
  23:     0x55f20933d353 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e2ccc70e3e3b65a
  24:     0x55f20931fc09 - std::rt::lang_start::{{closure}}::h207b49aedbc8af94
  25:     0x55f209b92bf9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  26:     0x55f209b92bf9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  27:     0x55f209b92bf9 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  28:     0x55f209b92bf9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  29:     0x55f209b92bf9 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  30:     0x55f2092fc222 - main
  31:     0x7f29da0400b3 - __libc_start_main
  32:     0x55f2092d0ffe - _start
  33:                0x0 - <unknown>
gfaestus: vendor/src/vk_mem_alloc.h:11791: void VmaDeviceMemoryBlock::Destroy(VmaAllocator): Assertion `m_pMetadata->IsEmpty() && "Some allocations were not freed before destruction of this memory block!"' failed.
Aborted (core dumped)
```

**Comment by AndreaGuarracino** [comment]
Just updated and re-tried:

```
INFO [winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
INFO [gfaestus::vulkan::init] Enumerating physical devices
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

INFO [gfaestus::vulkan::init] "Intel(R) UHD Graphics 630 (CFL GT2)"
INFO [gfaestus::vulkan::init] Selected physical device: "Intel(R) UHD Graphics 630 (CFL GT2)"
INFO [gfaestus] Loading GFA
INFO [gfaestus::gfa::load] loading GFA with 4011 nodes, 5481 edges
INFO [gfaestus::gfa::load] adding nodes
INFO [gfaestus::gfa::load] adding edges
INFO [gfaestus::gfa::load] adding paths
INFO [gfaestus::gfa::load] created path handles
INFO [gfaestus::universe] loading layout
INFO [gfaestus] layout bounding box	(1000.00, 1000.00)	(79896.92, 218997.72)
INFO [gfaestus] layout width: 78896.92	height: 217997.72
INFO [gfaestus] GFA loaded in 0.202 sec
INFO [gfaestus] Loaded 4011 nodes	8022 points
spawning reactor task
spawning reactor task
spawning reactor task
spawning reactor task
spawning reactor task
WARN [gfaestus] using the isoline edge renderer
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
ERROR [winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 149,
    minor_code: 4,
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/guarracino/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/window.rs:1006:14
stack backtrace:
   0:     0x55b0974f8160 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b0974f8160 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b0974f8160 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b0974f8160 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b09751cd5c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55b0974f4d45 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55b0974fa25b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b0974fa25b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b0974fa25b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55b0974f9d31 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55b0974fa924 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55b0974fa407 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x55b0974f865c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b0974fa369 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55b096f46a91 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55b096f46b83 - core::result::unwrap_failed::h6160d2b4bfbb0e87
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
  16:     0x55b0973abf1f - winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical::h949c427f9e40ca03
  17:     0x55b096f72a1e - gfaestus::main::{{closure}}::h6c2540870a2d953d
  18:     0x55b096f5cd70 - winit::platform_impl::platform::x11::EventLoop<T>::run::h4945ef2c862fedb5
  19:     0x55b096f6d3d6 - winit::platform_impl::platform::EventLoop<T>::run::h9506fca86bdbf60f
  20:     0x55b096fb6b02 - winit::event_loop::EventLoop<T>::run::h62e34e6d2aa61205
  21:     0x55b096fbc4a0 - gfaestus::main::h361aac6ce17417da
  22:     0x55b096f532a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5e858bdbd7796da8
  23:     0x55b096f8c239 - std::rt::lang_start::{{closure}}::heafa717c6da1bb0b
  24:     0x55b0974faf29 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  25:     0x55b0974faf29 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  26:     0x55b0974faf29 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  27:     0x55b0974faf29 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  28:     0x55b0974faf29 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  29:     0x55b096fbd1a2 - main
  30:     0x7f99e73d30b3 - __libc_start_main
  31:     0x55b096f4726e - _start
  32:                0x0 - <unknown>
gfaestus: vendor/src/vk_mem_alloc.h:11791: void VmaDeviceMemoryBlock::Destroy(VmaAllocator): Assertion `m_pMetadata->IsEmpty() && "Some allocations were not freed before destruction of this memory block!"' failed.
Aborted (core dumped)
```

Auff

**Comment by AndreaGuarracino** [comment]
From @chfi's tips: for `Ubuntu` users with a dedicated Nvidia GPU, put this before running `gfaestus`:

```
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
```
